# Default values for namespace-as-a-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

requester:
  name: ken@kenmoini.com
  type: User

naasConfig:
  - name: prod-app
    namespaces:
      - prod-primary
      - prod-secondary
    tshirtSize: large
    environment: production
    capabilities:
      - monitoring
    # groupAccess:
    #   - my-group-name

  - name: staging-app
    namespaces:
      - my-staging-namespace
    tshirtSize: medium
    environment: staging
    capabilities:
      - monitoring
      - virtualization
    groupAccess:
      - my-group-name

  - name: dev-app
    namespaces:
      - my-dev-namespace
    tshirtSize: small
    environment: development
    capabilities:
      - monitoring
      - virtualization
      - devspaces
    groupAccess:
      - my-group-name

# Other example potential config values:
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
