{{- if .Values.deployTestJobs }}
{{- $rootVar := . -}}
{{- $baseValues := .Values -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eip-reader
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - k8s.ovn.org
      - k8s.ovn.org/v1
    resources:
      - egressip
      - egressips
    verbs:
      - get
      - list
      - watch
{{- range .Values.egressIPList }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eip-test-{{ .name }}
  namespace: eip-test-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eip-test
  namespace: eip-test-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - create
      - delete
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eip-test
  namespace: eip-test-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eip-test
subjects:
  - kind: ServiceAccount
    name: eip-test-{{ .name }}
    namespace: eip-test-{{ .name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eip-test-reader
  # namespace: eip-test-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eip-reader
subjects:
  - kind: ServiceAccount
    name: eip-test-{{ .name }}
    namespace: eip-test-{{ .name }}
  - kind: ServiceAccount
    name: default
    namespace: eip-test-{{ .name }}
{{- end }}
{{- end }}