{{- if .Values.deployTestJobs }}
{{- $rootVar := . -}}
{{- $baseValues := .Values -}}
{{- range .Values.egressIPList }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eip-test-{{ .name }}
  namespace: eip-test-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=true,Replace=true
  labels:
    {{- include "egressip.labels" $rootVar | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
            - name: TARGET_ENDPOINT
              value: "{{ $baseValues.targetCURLTestEndpoint }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /bin/bash
            - -c
            - |
              curl -kv --max-time 10 $TARGET_ENDPOINT/$POD_NAME || exit 1
          name: curl-test

          imagePullPolicy: IfNotPresent
          name: curl-test
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
{{ end }}
{{ end }}