{{- if .Values.createEgressIPs }}
{{- $rootVar := . -}}
{{- $baseValues := .Values -}}
{{- range .Values.egressIPList }}
---
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "egressip.labels" $rootVar | nindent 4 }}
spec:
  egressIPs:
    {{- range .egressIPs }}
    - {{ . }}
    {{- end }}
  namespaceSelector:
    matchLabels:
{{- range $index, $label := .selector.matchLabels }}
      {{ $index }}: {{ $label | quote }}
{{- end }}

{{- if .podSelector }}
{{- with .podSelector }}
  podSelector:
{{- if .matchLabels }}
    matchLabels:
{{- range $index, $label := .matchLabels }}
      {{ $index }}: {{ $label | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
