{{- if .Values.deployTestJobs }}
{{- $rootVar := . -}}
{{- $baseValues := .Values -}}
{{- range .Values.egressIPList }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: eip-test-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=true
  labels:
    {{- include "egressip.labels" $rootVar | nindent 4 }}
{{- range $index, $label := .selector.matchLabels }}
    {{ $index }}: {{ $label | quote }}
{{- end }}
{{- end }}
{{- end }}