{{- if gt (len .Values.interfaceConfigurations) 0 }}
{{- $rootVar := . -}}
{{- $baseValues := .Values -}}
{{- range .Values.interfaceConfigurations }}
{{ if not .skipNADCreation }}
{{- if gt (len .vlanStack) 0 }}
{{- $interfaceConfig := . }}
{{- range .vlanStack }}
{{ if not .skipNADCreation }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vmnet{{ .vlanID }}-{{ .name }}
  namespace: default
  labels:
    {{- include "ocp-networking.labels" $rootVar | nindent 4 }}
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "mtu": {{ .mtu | default 1500 }},
      "name": "vmnet{{ .vlanID }}-{{ .name }}",
      "netAttachDefName": "default/vmnet{{ .vlanID }}-{{ .name }}",
      "physicalNetworkName": "vmnet{{ .vlanID }}-{{ .name }}"
    }

{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}