# Default values for egressip.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployTestJobs: true
targetCURLTestEndpoint: "https://something:8080"

createEgressIPs: true
egressIPList:
- name: prod
  egressIPs:
  - 1.2.3.4
  - 4.5.6.7
  selector:
    matchLabels:
      env: prod
- name: non-prod
  egressIPs:
  - 2.3.4.5
  - 7.8.9.1
  selector:
    matchLabels:
      env: non-prod
  
## Defaults that aren't entirely used

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
